### ISSUE TITLE
Possibly Missing Documentation

### ISSUE THREAD

**Issue by Philosyang** [SETT-Centre-Data-and-AI/Pteredactyl#6]
According to the [huggingface page](https://huggingface.co/spaces/MattStammers/pteredactyl_PII) as well as the [PyPI page](https://pypi.org/project/pteredactyl/), it seems that there was supposed to be a documentation for Pteredactyl hosted at https://mattstammers.github.io/Pteredactyl. However, the github.io site cannot be found.
I wonder if it is an intentional pull down or a work in progress.

Best of luck.

**Comment by MattStammers** [comment]
Hi, you are right, apologies about this. The docs have crashed so we will re-deploy them, thanks for raising this.

**Comment by MattStammers** [comment]
ok so the docs are up but they are deployed on my personal GitHub not the SETT one presently: https://mattstammers.github.io/Pteredactyl/

I will fix the backlinks
